# Generated by Django 5.1 on 2024-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tracksidebakery.com.au%2Fmelting-moment-biscuits&psig=AOvVaw2u03yeaC-ktood04PHmM2G&ust=1723798277703000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJD6lZXP9ocDFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
